arrowParens: avoid
bracketSpacing: true
bracketSameLine: false
endOfLine: lf
printWidth: 120
semi: false
singleQuote: true
jsxSingleQuote: false
quoteProps: as-needed
tabWidth: 2
trailingComma: es5
useTabs: false
singleAttributePerLine: false
